### ISSUE TITLE
Compatibility Craft 3

### ISSUE THREAD

**Issue by martijnvanonz** [imarc/craft-pickture#5]
Craft 3 (3.7.57) throw an error when creating the field.
Added a fix in this pull request https://github.com/imarc/craft-pickture/pull/4

Did not test with craft 4.

Hope this helps, have a nice day!

**Comment by khamer** [comment]
Tested with 4.2.4. Thanks @martijnvanonz !

**Comment by khamer** [comment]
Included in 1.1.4.
