### ISSUE TITLE
Plugin is not compatible with Craft ^4.4.0

### ISSUE THREAD

**Issue by psyn0nym** [imarc/craft-pickture#6]
The Pickture-Plugin is not compatible with Craft Version > 4.3.11 

`Declaration of Imarc\Pickture\fields\PicktureField::translatedOptions(bool $encode = false): array must be compatible with craft\fields\BaseOptionsField::translatedOptions(bool $encode = false, mixed $value = null, ?craft\base\ElementInterface $element = null): array`

**Comment by jorisnoo** [comment]
#7

**Comment by khamer** [comment]
Merged Pull #7 .
